### ISSUE TITLE
not working at all in ionic2 rc1

### ISSUE THREAD

**Issue by grapemix** [rollup/rollup-plugin-replace#11]
Hi,

We am not sure if we are missing something. Here is our case:

rollup.config.js:

var replace = require('rollup-plugin-replace');

.
.
.
  plugins: [
    builtins(),
    commonjs(),
    nodeResolve({
      module: true,
      jsnext: true,
      main: true,
      browser: true,
      extensions: ['.js']
    }),
    replace({
      exclude: 'node_modules/**',
      include: 'src/common/apiSrv.ts',
      values: {
      "API_HOST": "http://192.168.1.154:8000"
      }
      }),
.
.
.

OR 

```
replace({
  API_HOST: "http://192.168.1.154:8000"
  }),
```

apiSrv.ts:

console.log(API_HOST);

But we only got compile error. It seems the var is out of scope. We are so lost. Any ideas? ty

**Comment by mrkishi** [comment]
Hey @grapemix, you probably already moved on from this, but just in case anyone else comes across the same problem:

`rollup-plugin-replace` does a literal replacement. In that case, `console.log(API_HOST)` would be translated to `console.log(http://192.168.1.154:8000)`. To be able to use the variables in expressions, you should include the quotes, like so:

```js
replace({
    values: { API_HOST: `"http://192.168.1.154:8000"` }
})
```

**Comment by grapemix** [comment]
thx for your reply.
