### ISSUE TITLE
mixed-typed property names (some with delimiters)

### ISSUE THREAD

**Issue by yairEO** [rollup/rollup-plugin-replace#13]
How can I do mixed replace? (some variables have delimiters and some don't:

    replace({
        "delimiters" : [ '[', ']' ],
        "SERVERPATH" : JSON.stringify(config.serverPath),   // <---- requires delimiters
        "prodUrl"    : JSON.stringify(config.prodUrl),      // <---- requires delimiters
        "mocks/"     : JSON.stringify(config.serverPath + '/mocks/') 
    })

It was an utter failure to not use the `delimiters` key and trying to manually write `[SERVERPATH]` as key name. I also tried to escape the key like `\[SERVERPATH\]` without output success .

**Comment by yairEO** [comment]
figured it out, now facing new problems..

**Comment by mrkishi** [comment]
It's not possible without patching `rollup-plugin-replace`.

I [submitted a PR](https://github.com/rollup/rollup-plugin-replace/pull/9) that fixes this, but it hasn't been merged. Until then, I'm using that branch as a dependency instead of the published npm package.

**Comment by Rich-Harris** [comment]
Special characters are now supported in keys thanks to @mrkishi, so I'll close this. An alternative solution would be just to have two plugin instances — one with delimiters, one without.
