### ISSUE TITLE
Replace plugin resulting in stripping code but complaining about unused imports

### ISSUE THREAD

**Issue by gauntface** [rollup/rollup-plugin-replace#16]
I have a chunk of code along the lines of:

```javascript
import myFunc from 'module-example/myFunc';

if (process.env.NODE_ENV !== 'prod') {
  something();
}
```

This will build fine when `NODE_ENV !== prod` because `myFunc` is used. When I set `NODE_ENV` to 'prod', the if statement is stripped out and the build shows the warning:

```
'default' is imported from external module 'module-example/myFunc' but never used.
```

Ideally I'd like `myFunc` to be removed since the import isn't needed, but this warning message makes me assume that isn't the case. Is there a better way to do this?

**Comment by gauntface** [comment]
Ok, closing this. It started working after a different change. No idea what happened to be honest.

**Comment by Rich-Harris** [comment]
It should be possible to do this with the `pureExternalImports` option (which I've just realised is undocumented 😬 — details [here](https://github.com/rollup/rollup/pull/1388#issuecomment-305987700))

**Comment by gauntface** [comment]
Thanks @Rich-Harris I had a funny feeling there would be a way I was just missing what it was :+1:

**Comment by gauntface** [comment]
Closed to early. Just tried this and it seems that the warning is being called before this code is getting a chance to treat it as ok.

I.e. onWarn is called regardless of whether `pureExternalModules` is set as true or not.

This doesn't mean that the feature isn't working, just a slight overload of this feature would be "pure externals are ok to be unused".

Could be achieved with: `if ( this.isPureExternalModule( module.id ) ) return;` before warning.

```javascript
// while we're here, check for unused external imports
this.externalModules.forEach( module => {
	const unused = Object.keys( module.declarations )
		.filter( name => name !== '*' )
		.filter( name => !module.declarations[ name ].included && !module.declarations[ name ].reexported );

	if ( unused.length === 0 ) return;
	if ( this.isPureExternalModule( module.id ) ) return;

	const names = unused.length === 1 ?
		`'${unused[ 0 ]}' is` :
		`${unused.slice( 0, -1 ).map( name => `'${name}'` ).join( ', ' )} and '${unused.slice( -1 )}' are`;

	this.warn( {
		code: 'UNUSED_EXTERNAL_IMPORT',
		source: module.id,
		names: unused,
		message: `${names} imported from external module '${module.id}' but never used`
	} );
} );
```

**Comment by yavorski** [comment]
You can make `import` optional by `env` with `replace` plugin.
The approach i have taken is to replace comments with `replace` plugin.

This is my vendor js file, `redux-logger` and `redux-freeze` are only imported during development build.
In production build this is just a comment, which will be stripped out by `uglifyjs`:


```js
import * as redux from 'redux';
import thunk from 'redux-thunk';

/*@DEVELOPMENT
import logger from 'redux-logger';
import freeze from 'redux-freeze';
@DEVELOPMENT*/
```


And this is the `rollup` config, the replace configuration is just removing the comments in `dev` mode.

```js
const PRODUCTION = false; // you can read from `process.env.NODE_ENV` too
const DEVELOPMENT = !PRODUCTION;
...

plugins: [
  DEVELOPMENT && replace({ 
    delimiters: ['', ''], 
    values: { 
      '/*@DEVELOPMENT': '', 
      '@DEVELOPMENT*/': '' 
    } 
  }),
  resolve(),
  commonjs(),
  PRODUCTION && uglify()
]

```

This way all comments starting with `/*@DEVELOPMENT` and ending with `@DEVELOPMENT*/`, would be replaced with their contents during development build, and they will remain comments (as normal) during production build.

Cheers!

**Comment by wesleygrimes** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @wesleygrimes and request a re-open, and we'll be happy to oblige.
