### ISSUE TITLE
how to store values in a seperate json file

### ISSUE THREAD

**Issue by petterek** [rollup/rollup-plugin-replace#19]

**Comment by jordrake** [comment]
Since rollup config is executed javascript, you can just require a json file in for your values. For example:

```js
import replace from 'rollup-plugin-replace';

export default {
  // ...
  plugins: [
    replace({
      values: require('./your-file.json')
    })
  ]
};
```

**Comment by wesleygrimes** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @wesleygrimes and request a re-open, and we'll be happy to oblige.
