### ISSUE TITLE
Allow async functions

### ISSUE THREAD

**Issue by chrisguttandin** [rollup/rollup-plugin-replace#25]
Hi, I use this plugin to replace a worker with a string of its bundled source at build time. Unfortunately bundling the source of the worker is an asynchronous operation which is why I can't use this plugin without modifications.

The workaround I came up with is to add another custom plugin before this plugin in order to pause the overall execution of rollup. The custom plugin returns a promise which only gets resolved when the bundling of the worker is done. https://github.com/chrisguttandin/worker-timers/blob/2cfeb4d855c6184b54e230035c5be91be2b71c0a/config/rollup/bundle.js#L44

That all works great but it feels like a hack. I would like to propose adding support for async functions to this plugin to simplify use cases like that. I think it would be fully backwards compatible and won't introduce any breaking change.

Please let me know, if you like the idea. I'm happy to provide a pull request for it.

**Comment by lukastaegert** [comment]
I'm not sure I totally get it. You want the rollup build to pause until the raw data for this plugin has been generated?

Would it be an option to only start the rollup build once the worker string has been generated? Besides an object, rollup configs can also return promises resolving to an object. So the default export of `bundle.js` could return a promise that resolves to the actual config once the worker has been compiled.

**Comment by chrisguttandin** [comment]
Hi @lukastaegert, many thanks for looking into it. I didn't know that rollup accepts a promise which resolves with the config object. That is indeed all I need for my use case.

I will therefore close this issue. Many thanks again.
