### ISSUE TITLE
dotenv (.env file)

### ISSUE THREAD

**Issue by frederikhors** [rollup/rollup-plugin-replace#32]
Anything native with dotenv (https://github.com/motdotla/dotenv)?

**Comment by subdavis** [comment]
Can anything do this?

**Comment by TrySound** [comment]
You may use dotenv to get values and pass them to replace plugin.

**Comment by subdavis** [comment]
Thanks @TrySound, that seems pretty obvious now you've said it.   I should use dotenv from within my rollup config.  I'm coming off `vue-cli-service`, which takes a batteries-included approach to such things.

**Comment by TrySound** [comment]
I'm just not sure all variables from node environment should be available in browser bundle. I prefer to explicitly declare them with this plugin.

**Comment by ralyodio** [comment]
How do I access environment variables in the svelte code? I have replace working. But I don't know how to get the data.

**Comment by wesleygrimes** [comment]
Hi @frederikhors, it looks like @TrySound suggestion to use `dotenv` first to retrieve the values and then pass them to replace should work. If this isn't a viable solution, feel free to open a new issue in the github.com/rollup/org mono-repo.

The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @wesleygrimes and request a re-open, and we'll be happy to oblige.
