### ISSUE TITLE
Keywords inside comments should probably not get replaced

### ISSUE THREAD

**Issue by fyrak1s** [rollup/rollup-plugin-replace#34]
The current behavior is that `.replace` replaces any instance of a certain keyword.

This is of course intended however I wonder if content inside of HTML comments `<!-- -->` should actually be omitted? Since you might mention a keyword in a comment to describe it's behavior. 

And I might of course be wrong here, maybe there is a legitimate instance where you actually want to replace comments?

The reason I bring this up, is because this behavior happened to break my site, and it took me quite a long time to figure out the culprit. I mean logically, you would not expect a _comment_ to have actual influence on your sites behavior. Once I figured it out it made sense, however it is not really intuitive.

So this bugreport is really just to bring this to attention. If it is actually a desired behavior be free to close this bugreport.

**Comment by eventualbuddha** [comment]
I agree this would be a useful way for the plugin to operate. However, it’s probably better done as a separate plugin due to it being a breaking change. Maybe call it `rollup-plugin-define`?

**Comment by wesleygrimes** [comment]
This is related to #33 in that using AST would solve this issue. I have left some notes on thoughts over on that issue and would be interested to hear your feedback.

We are moving over to a new mono-repo concept for all of the Rollup plugins. If you are interested in seeing this idea pursued further, then I encourage you to open an issue up there as mentioned in the notes of #33.
