### ISSUE TITLE
Plugin isn't replacing anything

### ISSUE THREAD

**Issue by dominictobias** [rollup/rollup-plugin-replace#35]
Hey, I'm a bit confused about what this plugin is supposed to do. I thought I could use it to remove unoptimised code from the bundle like in Webpack but it doesn't seem to do anything for my UMD or ESM builds?

config:

```js
const extensions = [...DEFAULT_EXTENSIONS, '.ts', '.tsx'];
const globals = {
  react: 'React',
  'react-dom': 'ReactDOM',
};
const external = Object.keys(globals);
const input = 'src/index.tsx';

const plugins = [
  replace({
    'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV),
    ENVIRONMENT: JSON.stringify(process.env.NODE_ENV), // Tried this too
  }),
  nodeResolve({
    extensions,
    dedupe: external,
  }),
  commonjs({
    exclude: 'src/**',
  }),
  babel({
    exclude: 'node_modules/**',
    extensions,
  }),
];

export default [
  {
    input,
    output: {
      file: pkg.main,
      format: 'umd',
      name: 'flGrid',
      esModule: false,
      globals,
      sourcemap: true,
    },
    // plugins: plugins.concat(terser()),
    plugins,
    external,
  },
  {
    input,
    output: {
      file: pkg.module,
      format: 'esm',
      globals,
    },
    plugins,
    external,
  },
];
```

I have verified that `process.env.NODE_ENV` is `production` but if I look at the compiled code I see all the unstripped, unoptimised stuff. For example this is from Emotion the CSS lib:

![Screenshot 2019-08-24 at 17 17 25](https://user-images.githubusercontent.com/760314/63640019-0f423480-c693-11e9-992c-87392e19a621.png)

As you can see it seems that `process.env.NODE_ENV` hasn't been replaced and the unoptimised code is still there?

I am using the latest of all libraries as I just set this up.

**Comment by dominictobias** [comment]
Actually it's working in my userland code, but not for [Emotion](https://github.com/emotion-js/emotion) even with the [babel emotion](https://github.com/emotion-js/emotion/tree/master/packages/babel-plugin-emotion) plugin hmm

**Comment by dominictobias** [comment]
Here's a minimal repo of the bug: https://github.com/DominicTobias/emotion-rollup-dead-code

Notice how in my own code the conditional "I should be eliminated" has successfully been removed, but the Emotion stuff hasn't:

![Screenshot 2019-08-24 at 17 45 35](https://user-images.githubusercontent.com/760314/63640387-9db8b500-c697-11e9-8ebc-57dc2398a538.png)

**Comment by TrySound** [comment]
Try to put it after babel

**Comment by dominictobias** [comment]
Whoops thanks should have tried that, works!
