### ISSUE TITLE
How do I access the environment variable in my client side svelte codebase?

### ISSUE THREAD

**Issue by ralyodio** [rollup/rollup-plugin-replace#36]
I have this:

```
	plugins: [
		replace({
			'NODE_ENV': process.env.NODE_ENV
		}),
```

**Comment by wesleygrimes** [comment]
Hi @chovy,

I have seen issues in the past with this not working depending on the order of your `plugins` array. For instance, this would need to go after the babel plugin.

Thanks,
Wes

**Comment by wesleygrimes** [comment]
The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @wesleygrimes and request a re-open, and we'll be happy to oblige.
