### ISSUE TITLE
Run replacements after bundling

### ISSUE THREAD

**Issue by braco** [rollup/rollup-plugin-replace#6]
It would be nice if there was an option to run replacements after all the files were bundled/glued together.

Because of [common situations](https://www.npmjs.com/package/eslint-plugin-filenames) like this:

```
import Brand from './Brand.js';

export default class BrandSubclass extends Brand {}
```

combined with

```
replace({ Brand: 'NewBrand' })
```

which will yield:

```
Could not resolve './NewBrand' from ...
```

edit: I guess there would be situations that could require either first or last pass replacement. Maybe { ignoreImports: true } or something of that nature could be added, but rollup resolves all of this itself, so that seems like a waste.

**Comment by sinisterstumble** [comment]
@braco take a look at [rollup-plugin-post-replace](https://github.com/epiloque/rollup-plugin-post-replace)

**Comment by wesleygrimes** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @wesleygrimes and request a re-open, and we'll be happy to oblige.
